[[headers]]
  # Set Content-Type header for .jsx files
  for = "/*.jsx"
  [headers.values]
  Content-Type = "application/javascript"
  Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
